name: Reusable IaC

on:
  workflow_call:
    inputs:
      action:
        description: "plan | apply | destroy"
        type: string
        required: true
      environment:
        description: "dev | test | prod"
        type: string
        default: "dev"
      working-directory:
        description: "Terraform root config directory"
        type: string
        default: "iac/dev"
      aws-region:
        type: string
        default: "ap-south-1"
      role-to-assume:
        description: "IAM role ARN for GitHub OIDC"
        type: string
        required: true

permissions:
  id-token: write   # required for OIDC token
  contents: read

jobs:
  iac:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.13"

      - name: Init
        run: terraform init -input=false

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Apply
        if: inputs.action == 'apply'
        run: terraform apply -input=false -no-color -auto-approve tfplan

      - name: Destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -input=false -no-color -auto-approve
